### ISSUE TITLE
Support Minecraft 1.18

### ISSUE THREAD

**Issue by charims** [qumine/minecraft-server#41]
**Is your feature request related to a problem? Please describe.**
Minecraft 1.18 requires jdk17. When attempting to start a 1.18 server, I get the following message:
```Unsupported Java detected (60.0). This version of Minecraft requires at least Java 17. Check your Java version with the command 'java -version'.```

**Describe the solution you'd like**
Kindly provide a version of the container based off jdk17.

**Describe alternatives you've considered**
Perhaps could instead update the base container to jdk17, as it _should_ be backwards compatible with previous jars.

**Additional context**
https://www.minecraft.net/en-us/article/caves---cliffs--part-ii-out-today-java See section about java 17.

**Comment by 0SkillAllLuck** [comment]
1.18 support will be added in the next release. Currently working out how to get support for 1.7 - 1.18 versions into a single image

**Comment by 0SkillAllLuck** [comment]
1.18 is now supported. Java17 is installed by default if issues occur with certain mods/plugins please fallback to the old version and open an issue again.

**Comment by charims** [comment]
Thank you!
