### ISSUE TITLE
Allow to set labels & annotations on the deployment / stateful set

### ISSUE THREAD

**Issue by nilathedragon** [qumine/minecraft-server#73]
**Is your feature request related to a problem? Please describe.**
For some cluster behaviour control, I need to set labels and annotations on the deployment / stateful set. Currently you can only set labels and annotations for the pods.

**Describe the solution you'd like**
A YAML option to add labels and annotations to the deployment / stateful set

**Comment by 0SkillAllLuck** [comment]
Fixed in https://github.com/qumine/charts/commit/4f55a1b67056a0eefc7610f294908155f56e8f7f
